### ISSUE TITLE
Missing MLPERF BERT training hyperparameters in mlperf-logging's constants.py

### ISSUE THREAD

**Issue by lshao2** [mlcommons/logging#106]
Hello, although there are multiple hyper-parameters required by mlperf training rules for BERT model (https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#91-hyperparameters),
we do not see bert in the list of benchmark names, and we do not see bert's hyperparameters such as opt_learning_rate_training_steps, num_warmup_steps, start_warmup_step, opt_lamb_weight_decay_rate, etc in the list in https://github.com/mlcommons/logging/blob/master/mlperf_logging/mllog/constants.py.

**Comment by xyhuang** [comment]
fixed by #113
