### ISSUE TITLE
How to use compliance_checker

### ISSUE THREAD

**Issue by tkunlin** [mlcommons/logging#130]
I'm new to this. 

When i use the command as below

python -m mlperf_logging.compliance_checker --config ./1.0.0/common.yaml --ruleset ./mlp_parset/ruleset_060.py /home/gigabyte/submissions_training_v1.0/GIGABYTE/results/G492-ZD2_A100_20210517.mxnet/resnet/result_0.txt

==========================================================================
![image](https://user-images.githubusercontent.com/4994259/118923870-d2da6000-b96e-11eb-82f7-b4497dab8553.png)

Anyone can tell me how to fix ?

In the document no any example and also no description for ruleset
Refer: 
https://github.com/mlcommons/logging/tree/master/mlperf_logging/compliance_checker

**Comment by emizan76** [comment]
Sorry for the late answer, this unfortunately went to spam. You are using the wrong ruleset -- it should be 1.0.0

**Comment by emizan76** [comment]
OK, I ran the compliance checker on that file. It is fine. The command line should have been:
python3 -m mlperf_logging.compliance_checker ~/submission_training_1.0/GIGABYTE/results/G492-ZD2_A100_20210517.mxnet/resnet/result_0.txt

If you really want to set the ruleset, you should have added --ruleset 1.0.0 (with 0.6.0 it will fail)

**Comment by xyhuang** [comment]
we are closing this for now, if there's any further questions please feel free to reopen it.
