### ISSUE TITLE
Make README.md more useful to new users

### ISSUE THREAD

**Issue by matthew-frank** [mlcommons/logging#137]
The top level README.md should describe how to run (or at least find) package checker and result summarizer, instead of having pointers to compliance checker and system_desc_checker (which are both invoked through package checker).

**Comment by emizan76** [comment]
Good point, we will fix that.

**Comment by emizan76** [comment]
Matt, let us know if you are OK with additions to the README file and we can close this

**Comment by xyhuang** [comment]
fixed
