### ISSUE TITLE
Detect results/<system>/<benchmark>/result*.log in addition to results/<system>/<benchmark>/result*.txt

### ISSUE THREAD

**Issue by matthew-frank** [mlcommons/logging#138]
Many submitters in the v1.0 round made the mistake of naming their result logs
`results/<system>/<benchmark>/result*.log`
instead of
`results/<system>/<benchmark>/result*.txt`

But the .log files are silently ignored by the checkers and the result summarizer, making it look like the submitter didn't submit a benchmark result for that system.

Either (a) every file in `results/<system>/<benchmark>/*` should be treated as a result file or (b) the checker should issue an error for every file that doesn't belong in the `results/<system>/<benchmark>/*` directory.  At the very least, we should be more flexible about the extension on the results files to accommodate this very common difference.

**Comment by emizan76** [comment]
For the time being we are going to emit an error if no files are found. Supporting different directory structures is also possible but also more error-prone, we will bring it up with the training WG after 1.0 reviews finish.

**Comment by emizan76** [comment]
Some suggestions: Have a warning?

Supporting multiple extensions will likely not solve the problem.

**Comment by xyhuang** [comment]
Infra WG: add a warning/error suggesting to rename the files, but do not add support for additional extensions.

**Comment by matthew-frank** [comment]
Does this mean we are agreed that:
> the checker should issue an error for every file that doesn't belong in the `results/<system>/<benchmark>/*` directory
?

**Comment by emizan76** [comment]
If the proper files are not in the directory an error will be issued. Also if unexpected files are found in the directory, again an error will be issued.

**Comment by xyhuang** [comment]
addressed by #149
