### ISSUE TITLE
missing model_bn_span in schema for rcp_checker resnet hyperparams

### ISSUE THREAD

**Issue by matthew-frank** [mlcommons/logging#142]
In Submission 1.0 there are examples of various competitors having trouble reproducing various RCPs on the resnet reference code.  The problem is that the list of Hyperparameters in https://github.com/mlcommons/logging/blob/master/mlperf_logging/rcp_checker/1.0.0/rcps_resnet.json is missing the hyperparameter `model_bn_span`, which impacts convergence.  To make the RCPs reproducible, this information should be added. 

Additional info:
`model_bn_span` is one of the hyperparameters listed in https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#91-hyperparameters.

The reproduction issues are:

at global batch 3264:
* https://github.com/mlcommons/submission_training_1.0/issues/112
* https://github.com/mlcommons/submission_training_1.0/issues/118

at global batch 32768:
* https://github.com/mlcommons/submission_training_1.0/issues/88
* https://github.com/mlcommons/submission_training_1.0/issues/117

**Comment by xyhuang** [comment]
addressed by #149

**Comment by emizan76** [comment]
Matt, back to you, we will need model_bn_span for NVDA RCPs that were checked in during submission/review time. Or send me the values and I will add them in.

**Comment by shangw-nvidia** [comment]
> Matt, back to you, we will need model_bn_span for NVDA RCPs that were checked in during submission/review time. Or send me the values and I will add them in.

I just submitted PR #154 for bs=3264. I saw that the bn_span for bs=32768 already exists in our code.
