### ISSUE TITLE
Add missing RCPs for RNN-T

### ISSUE THREAD

**Issue by mwawrzos** [mlcommons/logging#147]
In https://github.com/mlcommons/logging/pull/146 only BS=2048 RCPs are updated. We need to update new numbers for reminder configs.

**Comment by qpjaada** [comment]
Since we are updating the RCPs anyway, we would like to request relaxing the WER requirement slightly. With our experiments, we are finding it extremely challenging to observe stable convergence to the required WER (although we are able to get extremely close).

**Comment by emizan76** [comment]
You mean you are failing the RCP test?

**Comment by qpjaada** [comment]
@emizan76 - we fail to reach the target WER although our implementation seems to be exactly the same as reference.
