### ISSUE TITLE
[Package Checker] Incorrect log naming convention check

### ISSUE THREAD

**Issue by shangw-nvidia** [mlcommons/logging#158]
https://github.com/mlcommons/logging/blob/master/mlperf_logging/package_checker/package_checker.py#L94

The check should be `if len(all_files) > len(result_files)` and it should be outside of the `if len(result_files) != benchmark_file_counts[benchmark]:` scope.

**Comment by emizan76** [comment]
Can you provide an example when the current scheme breaks ? I find it hard to understand without a case that highlights the problem.

**Comment by shangw-nvidia** [comment]
Currently, as long as `len(result_files) != benchmark_file_counts[benchmark]` is met, the `but some do not conform to naming convention` will always be printed because `len(all_files) > 0` is always true (unless the submitter submitted an empty folder). But `len(result_files) != benchmark_file_counts[benchmark]` only means that the submitter was not submitting the right amount of `result_*.txt` files.

**Comment by shangw-nvidia** [comment]
In a different scenario, let say `benchmark_file_counts[benchmark]` is 2 and the result folder contains `result_1.txt`, `result_2.txt` and `foo.txt`. Technically speaking, this submission is fine if we discard `foo.txt`, but `foo.txt` indeed does not conform to the naming convention. Currently, no warning would be printed in this case because `len(result_files) == benchmark_file_counts[benchmark]`.

**Comment by shangw-nvidia** [comment]
In summary, `len(result_files) != benchmark_file_counts[benchmark]` and `do not conform to naming convention` should be independent checks.

**Comment by emizan76** [comment]
I see. Doing the checks in that way was actually my intention. You can change it if you like it. I do not have a problem either way.

**Comment by xyhuang** [comment]
fixed in #161
