### ISSUE TITLE
[Result Summarizer] result summarizer returns instance_scale=0.0 for logs from CPU-based systems

### ISSUE THREAD

**Issue by koichishirahata** [mlcommons/logging#165]
@azrael417 
In result_summarizer.py, `_query_instance_scale` in `_compute_weak_scaling_scores` returns 0 for CPU-based systems. This is because the function assumes positive integer for `accelerators_per_node`, but a CPU-based system has no accelerators and `accelerators_per_node` is set to 0. 
A possible workaround is to add some lines setting `accelerators_per_node=1` when `accelerators_per_node` in a log is 0, just before the following line: 
https://github.com/mlcommons/logging/blob/master/mlperf_logging/result_summarizer/result_summarizer.py#L165

**Comment by shangw-nvidia** [comment]
Just put the number of CPUs in the `accelerators_per_node` field in system description json.

If you are using CPUs to accelerate, by definition, CPU is your accelerator.

**Comment by shangw-nvidia** [comment]
This issue is addressed in PR #168 .

**Comment by shangw-nvidia** [comment]
Fixed in #168
