### ISSUE TITLE
[compliance checker] logging features from Python 3.9

### ISSUE THREAD

**Issue by mwawrzos** [mlcommons/logging#190]
In recent changes, the `logging encoding` argument is used:
https://github.com/mlcommons/logging/blob/4c57bc2aae30229b095cc24999e1d89404619bc8/mlperf_logging/compliance_checker/__main__.py#L9
According to the documentation, it was added in Python 3.9:
https://docs.python.org/3/library/logging.html
Our README claims to support Python 3.6.8:
https://github.com/mlcommons/logging/blob/4c57bc2aae30229b095cc24999e1d89404619bc8/mlperf_logging/compliance_checker/README.md#tested-software-versions
We need to make a fix or update README.

**Comment by shangw-nvidia** [comment]
I'm wondering what the purpose is behind `encoding='utf-8'`?

**Comment by emizan76** [comment]
Marek, Shang, I removed utf-8 in PR #194 , let me know if that works for you now

**Comment by emizan76** [comment]
Try new release 1.10-rc4 or you can also use the head.
