### ISSUE TITLE
[package checker] weights initialization log fails 

### ISSUE THREAD

**Issue by qpjaada** [mlcommons/logging#197]
@emizan76 
Hi Elias - Eventhough the weights initialization is optional we are seeing errors like this:
```
Failed executing code POST code triggered by line :
:::MLLOG {"namespace": "resnet", "time_ms": 1634275681487, "event_type": "POINT_IN_TIME", "key": "weights_initialization", "value": null, "metadata": {"file": "train.py", "lineno": 662}}
```

We think its because of this check here:
https://github.com/mlcommons/logging/blob/master/mlperf_logging/compliance_checker/training_1.1.0/closed_resnet.yaml#L10

If we add an entry `"tensor": "all"` to the metadata, the compliance check passes. We just wanted to make sure if this is an acceptable workaround if we do not log all individual weight initializations.

**Comment by emizan76** [comment]
Yes, I was afraid something like that may happen with weight initialization. The reason is lack of testing -- I did not look into this case when I turned this into a warning. So you can either use the solution you propose, or remove all weights_initialization files from your log.
