### ISSUE TITLE
Allow applying a scaling-factor to results for automated RCP normalization

### ISSUE THREAD

**Issue by nv-rborkar** [mlcommons/logging#210]
In the past few rounds we have come across instances where the final results had to be scaled to account for RCP failure.

It will be convenient to have an ability to pass a scaling-factor (default-1.0) argument to result summarizer for automatic scaling of results when needed.

For example it can be an additional mllog key-value appended to the end of result logs or a json input to result-summarizer script.

**Comment by nv-rborkar** [comment]
@emizan76 what do you think about above? In the past few rounds we either had to manually update the result spreadsheet or time-stamps to account for RCP normalization which is not ideal.

**Comment by emizan76** [comment]
Just updating this to reflect implementation and how it is going to be used:
- If a json file will a "sclaing" factor filed is provided in the result dir of the benchmark that will be normalized, then the score is sclaed by that factor.
- If not, the score is NOT scaled.

Using a json file is easier and more robust than having a line inside the log file.
