### ISSUE TITLE
Incompatibility with python versions < 3.7

### ISSUE THREAD

**Issue by eyal-lavee** [mlcommons/logging#232]
Recent changes in the logging have broken compatibility with older python versions (<3.7) due to use of new features in sub-process api.

from [https://docs.python.org/3/library/subprocess.html](https://docs.python.org/3/library/subprocess.html):
  Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.

here is the patch to restore support for python < 3.7:
```
diff --git a/mlperf_logging/repo_checker/repo_checker.py b/mlperf_logging/repo_checker/repo_checker.py
index 1f7791e..e53834b 100644
--- a/mlperf_logging/repo_checker/repo_checker.py
+++ b/mlperf_logging/repo_checker/repo_checker.py
@@ -37,8 +37,9 @@ def _check_file_sizes(submission_dir):
             "-size",
             "+50M",
         ],
-        capture_output=True,
-        text=True,
+        stdout=subprocess.PIPE,
+        stderr=subprocess.PIPE,
+        universal_newlines=True,
     )
     if len(out.stdout) != 0:
         logging.error('Files > 50MB: %s', out.stdout)
```

**Comment by emizan76** [comment]
Thanks Eyal, we'll check this and make a PR.

**Comment by emizan76** [comment]
See PR #234
