### ISSUE TITLE
No hpc-2.0.0-rc1 tag

### ISSUE THREAD

**Issue by mmarcinkiewicz** [mlcommons/logging#260]
Hi we are ~2 weeks from the HPC submission and the submission tag is still missing. 
Is there a way you can create it sooner than later? People start to run their submission runs and having a moving target (as the hpc_config_2.0 branch got removed) is highly suboptimal

**Comment by pgmpablo157321** [comment]
The branch hpc_2.0.0_config got merge into master here https://github.com/mlcommons/logging/pull/255. So I think we can create the tag from master now.

@sparticlesteve @memani1 @xyhuang What do you think?

**Comment by sparticlesteve** [comment]
Tag or branch? RCP pull requests are still incoming. A tag would help for producing logs, though.

**Comment by mmarcinkiewicz** [comment]
Generally, we need a tag. Training at v2.0 had four rc tags, that were updated with new RCPs (and few bugfixes) as the time to submission approached. There's nothing stopping us from doing a similar thing.

Using unpinned branch makes it hard to (a) reproduce, (b) risky. If an erroneous commit appears it can make a full cluster of jobs fail, that, as you can imagine, is undesirable.

**Comment by sparticlesteve** [comment]
that all makes sense. We could have both, but it's clear we at least need tags.

**Comment by xyhuang** [comment]
hi all, we have just created tag 2.0.0 and that should include the recent changes for HPC.

**Comment by mmarcinkiewicz** [comment]
Thanks, closing. BTW I've opened a similar one for Training https://github.com/mlcommons/logging/issues/268
