### ISSUE TITLE
Bert checking fails on missing "opt_epsilon" - bug or feature?

### ISSUE THREAD

**Issue by plvlnisse** [mlcommons/logging#277]
When checking the Bert run the checker complains that opt_epsilon is not present. We can not find opt_epsilon mentioned in any file in the /scripts directory. Is the check incorrect or have we missed something fundamental when running the benchmarks?

```
INFO - Running compliance on file: 221011111823961650440_5.log
INFO -  Compliance checks: training_2.1.0/common.yaml
INFO -  Compliance checks: training_2.1.0/closed_common.yaml
INFO -  Compliance checks: training_2.1.0/closed_bert.yaml
WARNING -  Required EXACTLY_ONE occurrence of 'opt_epsilon' but found 0
ERROR - FAILED
** Logging output also at compliance_checker.log
```

**Comment by pgmpablo157321** [comment]
@plvlnisse https://github.com/mlcommons/logging/pull/270/files is this the correct renaming of the variable?

**Comment by plvlnisse** [comment]
Yes it is, but incorporating this now in the middle of submissions may
create new problems. We have renamed the variable in our output files
already.
