### ISSUE TITLE
[training_4.0][gpt3][compliance checker] wrong `compile_time_mins` for gpt3 task

### ISSUE THREAD

**Issue by ZhiyuLi-goog** [mlcommons/logging#366]
The `compile_time_mins` is 60min in gpt3 training according to [the training rule](https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#181-large-language-model-gpt3).

It isn't yet reflected in the compliance checker:
in [`mlperf_logging/compliance_checker/training_4.0.0/common.yaml`](https://github.com/mlcommons/logging/blob/master/mlperf_logging/compliance_checker/training_4.0.0/common.yaml#L45):
```
# `compile_time_mins` is 30min for all open tasks without covering the special case in gpt3

enqueue_config('training_4.0.0/{}_common.yaml'.format(v['value'])); s['compile_time_mins'] = 240 if v['value'] == 'open' else 30 
```

**Comment by hiwotadese** [comment]
60min is specific to v3.0
